SELECT *
FROM EvolutionInLastFiveYears Parent
WHERE SECTOR_ID = 11
  AND Name = 'Banana'
ORDER BY YEAR, MONTH ASC;

SELECT MONTH, PRODUCT_NAME, FIRST_YEAR_SALES, SECOND_YEAR_SALES, YEARS_COMPARISON
FROM SalesComparison
WHERE FIRST_YEAR = 2018
  AND SECOND_YEAR = 2017;

SELECT *
FROM MonthlySalesEvolutionByCultureType;

SELECT *
FROM MonthlySalesEvolutionByCultureTypeAndHub;