
    CREATE TABLE Operation(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR2(255) CHECK ( status = 'PENDENTE' OR status = 'COMPLETO' OR status = 'CANCELADO'),
    plot_id INTEGER NOT NULL
    );

    ALTER TABLE Operation ADD CONSTRAINT Fk_Operation_Plot FOREIGN KEY (plot_id) REFERENCES plot(id);


    select * from AuditLog order by operation_date;
    select * from EXPLORATION;
    select * from PLOT;
    select * from SYSTEMUSER;
    select * from OPERATION;

    DELETE FROM PLOT;
    DELETE FROM AUDITLOG;

    -- exploration
    INSERT INTO exploration(area) VALUES(50);
    INSERT INTO exploration(area) VALUES(150);
    INSERT INTO exploration(area) VALUES(500);
    INSERT INTO exploration(area) VALUES(250);
    INSERT INTO exploration(area) VALUES(350);
    COMMIT;

    -- user
    INSERT INTO SYSTEMUSER(email, password, exploration_id) VALUES ('1211511@isep.ipp.pt', '1234', 1);
    INSERT INTO SYSTEMUSER(email, password, exploration_id) VALUES ('1211512@isep.ipp.pt', '1234', 2);
    INSERT INTO SYSTEMUSER(email, password, exploration_id) VALUES ('1211513@isep.ipp.pt', '1234', 3);
    COMMIT;

    --plot
    INSERT INTO plot(exploration_id, designation,area) VALUES(1, 'sector',200);
    INSERT INTO plot(exploration_id, designation,area) VALUES(2, 'campo',1000);
    INSERT INTO plot(exploration_id, designation,area) VALUES(3, 'campo',750);
    INSERT INTO plot(exploration_id, designation,area) VALUES(4, 'sector',600);
    INSERT INTO plot(exploration_id, designation,area) VALUES(5, 'sector',500);
    INSERT INTO plot(exploration_id, designation,area) VALUES(5, 'sector',200);
    INSERT INTO plot(exploration_id, designation,area) VALUES(5, 'sector',1500);

    INSERT INTO OPERATION(status, plot_id) VALUES ('PENDENTE', 23);

    UPDATE Operation
    SET status = 'PENDENTE'
    WHERE id = 3;
    COMMIT;

    DELETE FROM Operation
    WHERE id = 3;
    COMMIT;

    select * from AuditLog order by operation_date;



/*
    alter table AUDITLOG
        drop constraint FK_PLOT;


 */

    UPDATE PLOT
    SET AREA = 50
    WHERE id = 22;
    COMMIT;

    DELETE FROM PLOT
    WHERE id = 22;
    COMMIT;