--eliminar tabelas(caso existam)
DROP TABLE ANIMALRATION CASCADE CONSTRAINTS PURGE;

DROP TABLE BASKETPRODUCT CASCADE CONSTRAINTS PURGE;
DROP TABLE BASKETORDER CASCADE CONSTRAINTS PURGE;
DROP TABLE BUILDING CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENT CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTINCIDENT CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTLEVELS CASCADE CONSTRAINTS PURGE;
DROP TABLE CLIENTLEVEL CASCADE CONSTRAINTS PURGE;
DROP TABLE CULTURE CASCADE CONSTRAINTS PURGE;

DROP TABLE DISTRIBUTIONHUB CASCADE CONSTRAINTS PURGE;
DROP TABLE GENERICELEMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE EXPLORATION CASCADE CONSTRAINTS PURGE;
DROP TABLE FIELDBOOK CASCADE CONSTRAINTS PURGE;
DROP TABLE HARVEST CASCADE CONSTRAINTS PURGE;


DROP TABLE IRRIGATION CASCADE CONSTRAINTS PURGE;

DROP TABLE METEREOLOGICSTATION CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDERDELIVERY CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDERPAYMENT CASCADE CONSTRAINTS PURGE;
DROP TABLE OPERATION CASCADE CONSTRAINTS PURGE;
DROP TABLE PLANTEDCULTURE CASCADE CONSTRAINTS PURGE;
DROP TABLE PLOT CASCADE CONSTRAINTS PURGE;

DROP TABLE PRODUCT CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCTIONFACTOR CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCTIONFACTORAPPLICATION CASCADE CONSTRAINTS PURGE;
DROP TABLE SENSOR CASCADE CONSTRAINTS PURGE;
DROP TABLE SENSORDATA CASCADE CONSTRAINTS PURGE;

DROP TABLE STOREDANIMALRATION CASCADE CONSTRAINTS PURGE;
DROP TABLE STOREDCULTURE CASCADE CONSTRAINTS PURGE;
DROP TABLE STOREDPRODUCTIONFACTOR CASCADE CONSTRAINTS PURGE;
DROP TABLE ELEMENTTYPE CASCADE CONSTRAINTS PURGE;
DROP TABLE TECHNICALSHEETASSOCIATION CASCADE CONSTRAINTS PURGE;

DROP TABLE TYPE CASCADE CONSTRAINTS PURGE;
DROP TABLE CULTURETYPES CASCADE CONSTRAINTS PURGE;
DROP TABLE PLOTRESTRICTIONS CASCADE CONSTRAINTS PURGE;
DROP TABLE SYSTEMUSER CASCADE CONSTRAINTS PURGE;
DROP TABLE AUDITLOG CASCADE CONSTRAINTS PURGE;
DROP TABLE INPUT_HUB CASCADE CONSTRAINTS PURGE;
DROP TABLE OPERATION_CALENDAR CASCADE CONSTRAINTS PURGE;
DROP TABLE input_sensor CASCADE CONSTRAINTS PURGE;
DROP TABLE SENSORREGIST CASCADE CONSTRAINTS PURGE;
DROP TABLE SENSORERROR CASCADE CONSTRAINTS PURGE;


--criar tables

CREATE TABLE Exploration( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area INTEGER NOT NULL
);


CREATE TABLE Building( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exploration_id INTEGER  NOT NULL,
  type VARCHAR(255)
);

CREATE TABLE Culture( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plant_species VARCHAR(255)  NOT NULL,
  type_id INTEGER NOT NULL
);


CREATE TABLE CultureTypes( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_modification_date date
);


CREATE TABLE Type( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type_designation varchar(255) NOT NULL,
  culture_types_id INTEGER NOT NULL
);

CREATE TABLE Plot(  
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exploration_id INTEGER  NOT NULL,
  designation VARCHAR(255)  NOT NULL,
  area INTEGER  NOT NULL
);

CREATE TABLE TechnicalSheetAssociation( 
  production_factor_id INTEGER NOT NULL,
  generic_elemnet_id INTEGER NOT NULL,
  quantity INTEGER,
  PRIMARY KEY(production_factor_id,generic_elemnet_id)
);

CREATE TABLE GenericElement( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  element_type_id INTEGER NOT NULL
);

CREATE TABLE ElementType( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  designation VARCHAR(255)
);

CREATE TABLE ProductionFactor( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classification VARCHAR(255) NOT NULL,
  comercial_name VARCHAR(255) NOT NULL,
  formulation VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  provider VARCHAR(255) NOT NULL
);

CREATE TABLE AnimalRation( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  animal VARCHAR(255) NOT NULL
);

CREATE TABLE StoredAnimalRation( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantity INTEGER NOT NULL CHECK ( quantity >= 0 ),
  building_id INTEGER NOT NULL,
  animal_ration_id INTEGER NOT NULL
);

CREATE TABLE StoredProductionFactor( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantity INTEGER NOT NULL CHECK ( quantity >= 0 ),
  building_id INTEGER NOT NULL,
  production_factor_id INTEGER NOT NULL
);

CREATE TABLE StoredCulture(  
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantity INTEGER NOT NULL CHECK ( quantity >= 0 ),
  building_id INTEGER NOT NULL,
  culture_id INTEGER NOT NULL
);


CREATE TABLE MetereologicStation( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exploration_id INTEGER NOT NULL
);


CREATE TABLE ClientIncident( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER NOT NULL,
  value INTEGER NOT NULL CHECK (value>=0),
  date_incident DATE NOT NULL,
  status VARCHAR(255) NOT NULL,
  remedied_date DATE NOT NULL
);

CREATE TABLE Client( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exploration_id INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  fiscal_number INTEGER NOT NULL UNIQUE CHECK (fiscal_number>99999999 AND fiscal_number<1000000000),
  email VARCHAR(100) NOT NULL UNIQUE CHECK (email LIKE '%_@%__%.__%'),
  plafond INTEGER NOT NULL,
  client_level VARCHAR(1) NOT NULL CHECK ( client_level = 'A' OR client_level = 'B' OR client_level = 'C'),
  incident_number INTEGER,
  last_incident_date DATE,
  amount_of_orders_last_year INTEGER NOT NULL CHECK (amount_of_orders_last_year>=0),
  total_orders_value_last_year INTEGER NOT NULL CHECK (total_orders_value_last_year>=0),
  level_id INTEGER NOT NULL,
  correspondence_address VARCHAR(100) NOT NULL ,
  default_delivery_address VARCHAR(100) NOT NULL,
  postal_code VARCHAR(100) NOT NULL,
  default_hub_id INTEGER NOT NULL
);

CREATE TABLE ClientLevels( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_modification_date DATE
);

CREATE TABLE ClientLevel( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_level_id INTEGER NOT NULL,
  designation VARCHAR(255) NOT NULL
);

CREATE TABLE BasketOrder( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id INTEGER NOT NULL,
  delivery_address VARCHAR(100) NOT NULL,
  status VARCHAR(255) NOT NULL CHECK ( status = 'Paga' OR status = 'Entregue' OR status = 'Registada'),
  order_date DATE NOT NULL,
  total_amount INTEGER NOT NULL CHECK (total_amount>=0),
  pickup_hub_id INTEGER NOT NULL
);

CREATE TABLE BasketProduct( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quantity INTEGER CHECK(quantity>=0),
  basket_order_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL
);

CREATE TABLE OrderDelivery( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delivery_date DATE NOT NULL,
  basket_order_id INTEGER NOT NULL
);

CREATE TABLE OrderPayment( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_date DATE NOT NULL,
  basket_order_id INTEGER NOT NULL
);

CREATE TABLE FieldBook ( 
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exploration_id INTEGER NOT NULL,
  creation_date DATE NOT NULL,
  end_date DATE NOT NULL,
  writer VARCHAR(255) NOT NULL
);

CREATE TABLE ProductionFactorApplication ( 
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_factor_id INTEGER DEFAULT 1,
  type                 INTEGER,
  field_book_id        INTEGER DEFAULT 1,
  quantity_applied     INTEGER,
  operation_id 	     INTEGER NOT NULL
);


CREATE TABLE Irrigation ( 
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  irrigation_minutes  INTEGER NOT NULL CHECK (irrigation_minutes>=0),
  type                INTEGER,
  field_book_id       INTEGER DEFAULT 1,
  operation_id 	    INTEGER NOT NULL	
);

CREATE TABLE PlantedCulture( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plot_id INTEGER NOT NULL,
  culture_id INTEGER NOT NULL,
  begin_date DATE, 
  end_date  DATE  
);

CREATE TABLE Harvest( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plot_id INTEGER NOT NULL,
  product_id INTEGER NOT NULL,
  field_book_id INTEGER NOT NULL,
  harvest_date date NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity>=0)
);

CREATE TABLE Product ( 
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price     INTEGER NOT NULL CHECK (price>=0),
  name      varchar(255) NOT NULL,
  type      varchar(255) NOT NULL,
  culture_id INTEGER NOT NULL
);

CREATE TABLE DistributionHub( 
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  address VARCHAR(255) NOT NULL,
  hub_code VARCHAR(255) NOT NULL
);

CREATE TABLE PlotRestrictions( 
  plot_id INTEGER NOT NULL,
  production_factor_id INTEGER NOT NULL,
  restriction_begining_date DATE NOT NULL,
  restriction_end_date DATE,
  PRIMARY KEY (plot_id,production_factor_id)
);

CREATE TABLE SystemUser(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL CHECK (email LIKE '%_@%%.%'),
  password VARCHAR(255) NOT NULL,
  exploration_id INTEGER NOT NULL
);

CREATE TABLE AuditLog (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_date       DATE,
    type           VARCHAR(255),
    plot_id         INTEGER NOT NULL,
    system_user_id     INTEGER NOT NULL
);

CREATE TABLE Operation(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR2(255) CHECK ( status = 'PENDENTE' OR status = 'COMPLETO' OR status = 'CANCELADO'),
    plot_id INTEGER NOT NULL
);
CREATE TABLE Operation_Calendar(
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id INTEGER NOT NULL,
  start_date   DATE NOT NULL,
  end_date     DATE
);


CREATE TABLE input_hub(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loc_id VARCHAR(255),
  lon FLOAT,
  lat FLOAT,
  id_hub INTEGER,
  clients_productors VARCHAR(255) CHECK (clients_productors LIKE 'E%' or clients_productors LIKE 'P%')
);

Create Table SENSORDATA(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RECORD_DATE Date NOT NULL,
  sensor_id VARCHAR2(5) NOT NULL,
  value INTEGER not NULL
);

CREATE TABLE SENSORREGIST (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    read_date DATE ,
    read_reg INTEGER,
    ins_reg INTEGER ,
    not_read_reg INTEGER ,
    sensor_data_id INTEGER DEFAULT 1,
    field_book_id INTEGER DEFAULT 1

);

CREATE TABLE SENSORERROR(
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id VARCHAR2(5) NOT NULL,
    total_errors INTEGER,
    sensor_data_id INTEGER DEFAULT 1
);

CREATE Table SENSOR(
    id VARCHAR2(5) PRIMARY KEY,
    type VARCHAR2(2) NOT NULL,
    unique_Number VARCHAR2(2) UNIQUE NOT NULL,
    metereologic_station_id INTEGER DEFAULT 1,
    plot_id INTEGER DEFAULT 1
);

CREATE TABLE input_sensor(
    id INTEGER  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_string VARCHAR(25)
);


--chaves estrangeiras

ALTER TABLE Building ADD CONSTRAINT FK_Building_exploration FOREIGN KEY (exploration_id) REFERENCES Exploration (id) ON DELETE CASCADE;

ALTER TABLE Plot ADD CONSTRAINT FK_Plot_exploration FOREIGN KEY (exploration_id) REFERENCES Exploration (id) ON DELETE CASCADE;

ALTER TABLE GenericElement ADD CONSTRAINT FK_GenericElemnet_ElementType FOREIGN KEY (element_type_id) REFERENCES ElementType (id) ON DELETE CASCADE;

ALTER TABLE TechnicalSheetAssociation ADD CONSTRAINT FK_TechnicalSheetAssociation_ProductionFactor FOREIGN KEY (production_factor_id) REFERENCES ProductionFactor (id) ON DELETE CASCADE;
ALTER TABLE TechnicalSheetAssociation ADD CONSTRAINT FK_TechnicalSheetAssociation_GenericElement FOREIGN KEY (generic_elemnet_id) REFERENCES GenericElement (id) ON DELETE CASCADE;

ALTER TABLE StoredProductionFactor ADD CONSTRAINT FK_StoredProd_production FOREIGN KEY (production_factor_id) REFERENCES ProductionFactor (id) ON DELETE CASCADE;
ALTER TABLE StoredProductionFactor ADD CONSTRAINT FK_StoredProd_building FOREIGN KEY (building_id) REFERENCES Building (id) ON DELETE CASCADE;

ALTER TABLE StoredAnimalRation ADD CONSTRAINT FK_StoredRation_animal FOREIGN KEY (animal_ration_id) REFERENCES AnimalRation (id) ON DELETE CASCADE;
ALTER TABLE StoredAnimalRation ADD CONSTRAINT FK_StoredAnim_building FOREIGN KEY (building_id) REFERENCES Building (id) ON DELETE CASCADE;

ALTER TABLE StoredCulture ADD CONSTRAINT FK_StoredCulture_culture FOREIGN KEY (culture_id) REFERENCES Culture (id) ON DELETE CASCADE;
ALTER TABLE StoredCulture ADD CONSTRAINT FK_StoredCult_building FOREIGN KEY (building_id) REFERENCES Building (id) ON DELETE CASCADE;


ALTER TABLE MetereologicStation ADD CONSTRAINT FK_MetereologicStation_exploration FOREIGN KEY (exploration_id) REFERENCES Exploration (id) ON DELETE CASCADE;

ALTER TABLE ClientIncident ADD CONSTRAINT FK_ClientIncident_client FOREIGN KEY (client_id) REFERENCES Client (id) ON DELETE CASCADE;

ALTER TABLE BasketOrder ADD CONSTRAINT FK_BasketOrder_client FOREIGN KEY (client_id) REFERENCES Client (id) ON DELETE CASCADE;
ALTER TABLE BasketOrder ADD CONSTRAINT FK_BasketOrder_distributionHub FOREIGN KEY (pickup_hub_id) REFERENCES DistributionHub (id) ON DELETE CASCADE;

ALTER TABLE OrderPayment ADD CONSTRAINT FK_OrderPayme_order FOREIGN KEY (basket_order_id) REFERENCES BasketOrder (id) ON DELETE CASCADE;

ALTER TABLE OrderDelivery ADD CONSTRAINT FK_OrderDeliv_basket_order FOREIGN KEY (basket_order_id) REFERENCES BasketOrder (id) ON DELETE CASCADE;

ALTER TABLE Client ADD CONSTRAINT FK_Client_exploration FOREIGN KEY (exploration_id) REFERENCES Exploration (id) ON DELETE CASCADE;
ALTER TABLE Client ADD CONSTRAINT FK_Client_level FOREIGN KEY (level_id) REFERENCES ClientLevel (id) ON DELETE CASCADE;

ALTER TABLE FieldBook ADD CONSTRAINT FK_FieldBook_exploration FOREIGN KEY (exploration_id) REFERENCES Exploration (id) ON DELETE CASCADE;

ALTER TABLE ProductionFactorApplication ADD CONSTRAINT FK_Production_production FOREIGN KEY (production_factor_id) REFERENCES ProductionFactor (id) ON DELETE CASCADE;
ALTER TABLE ProductionFactorApplication ADD CONSTRAINT FK_ProductionFactorApplication_fieldBook FOREIGN KEY (field_book_id) REFERENCES FieldBook (id) ON DELETE CASCADE;


ALTER TABLE Irrigation ADD CONSTRAINT FK_Irrigation_fieldBook FOREIGN KEY (field_book_id) REFERENCES FieldBook (id) ON DELETE CASCADE;

ALTER TABLE PlantedCulture ADD CONSTRAINT FK_PlantedCulture_Plot FOREIGN KEY (plot_id) REFERENCES Plot (id) ON DELETE CASCADE;
ALTER TABLE PlantedCulture ADD CONSTRAINT FK_PlantedCulture_Culture FOREIGN KEY (culture_id) REFERENCES Culture (id) ON DELETE CASCADE;

ALTER TABLE Harvest ADD CONSTRAINT FK_Harvest_plot FOREIGN KEY (plot_id) REFERENCES Plot (id) ON DELETE CASCADE;
ALTER TABLE Harvest ADD CONSTRAINT FK_Harvest_Product FOREIGN KEY (product_id) REFERENCES Product (id) ON DELETE CASCADE;
ALTER TABLE Harvest ADD CONSTRAINT FK_Harvest_FieldBook FOREIGN KEY (field_book_id) REFERENCES FieldBook (id) ON DELETE CASCADE;

ALTER TABLE Culture ADD CONSTRAINT FK_Culture_Type FOREIGN KEY (type_id) REFERENCES Type (id) ON DELETE CASCADE;

ALTER TABLE Type ADD CONSTRAINT FK_Type_cultureTypes FOREIGN KEY (culture_types_id) REFERENCES CultureTypes (id) ON DELETE CASCADE;

ALTER TABLE Product ADD CONSTRAINT FK_Product_culture FOREIGN KEY (culture_id) REFERENCES Culture (id) ON DELETE CASCADE;

ALTER TABLE ClientLevel ADD CONSTRAINT FK_Level_clientLevels FOREIGN KEY (client_level_id) REFERENCES ClientLevels (id) ON DELETE CASCADE;

ALTER TABLE BasketProduct ADD CONSTRAINT FK_BasketProduct_basketOrder FOREIGN KEY (basket_order_id) REFERENCES BasketOrder (id) ON DELETE CASCADE;
ALTER TABLE BasketProduct ADD CONSTRAINT FK_BasketProduct_product FOREIGN KEY (product_id) REFERENCES Product (id) ON DELETE CASCADE;

ALTER TABLE PlotRestrictions ADD CONSTRAINT FK_PlotRestrictions_productionFactor FOREIGN KEY (production_factor_id) REFERENCES ProductionFactor (id) ON DELETE CASCADE;
ALTER TABLE PlotRestrictions ADD CONSTRAINT FK_PlotRestrictions_plot FOREIGN KEY (plot_id) REFERENCES Plot (id) ON DELETE CASCADE;
 
ALTER TABLE SystemUser ADD CONSTRAINT FK_SystemUser_exploration FOREIGN KEY (exploration_id) REFERENCES Exploration (id) ON DELETE CASCADE;

ALTER TABLE AuditLog ADD CONSTRAINT FK_System_User FOREIGN KEY (system_user_id) REFERENCES SystemUser (id) ON DELETE CASCADE;
ALTER TABLE AuditLog ADD CONSTRAINT Fk_Plot FOREIGN KEY (plot_id) REFERENCES Plot (id) ON DELETE CASCADE;

ALTER TABLE ProductionFactorApplication ADD CONSTRAINT FK_ProductionFactorApplication_Operation FOREIGN KEY (operation_id) REFERENCES Operation (id) ON DELETE CASCADE;

ALTER TABLE Irrigation ADD CONSTRAINT FK_Irrigation_Operation FOREIGN KEY (operation_id) REFERENCES Operation (id) ON DELETE CASCADE;

ALTER TABLE Input_hub ADD CONSTRAINT FK_input_hub_DistributionHub FOREIGN KEY (id_hub) REFERENCES DistributionHub (id) ON DELETE CASCADE;

ALTER TABLE Operation_Calendar ADD CONSTRAINT FK_Operation_Operation_Calendar FOREIGN KEY (operation_id) REFERENCES Operation(id);

ALTER TABLE Operation ADD CONSTRAINT Fk_Operation_Plot FOREIGN KEY (plot_id) REFERENCES plot(id);

ALTER TABLE SENSORDATA ADD CONSTRAINT FK_SensorData_Sensor FOREIGN KEY (sensor_id) REFERENCES SENSOR(id);

ALTER TABLE SENSOR ADD CONSTRAINT FK_Sensor_metereologicstation FOREIGN KEY (metereologic_station_id) REFERENCES METEREOLOGICSTATION(id);
ALTER TABLE SENSOR ADD CONSTRAINT FK_Sensor_plot FOREIGN KEY (plot_id) REFERENCES PLOT (id);

ALTER TABLE SENSORERROR ADD CONSTRAINT FK_Sensorerror_sensordata FOREIGN KEY (sensor_data_id) REFERENCES SENSORDATA(id);

ALTER TABLE SENSORREGIST ADD CONSTRAINT FK_Sensorregist_sensordata FOREIGN KEY (sensor_data_id) REFERENCES SENSORDATA(id);
ALTER TABLE SENSORREGIST ADD CONSTRAINT FK_Sensorregist_fieldbook FOREIGN KEY (field_book_id) REFERENCES FieldBook(id);




-- exploration
INSERT INTO exploration(area) VALUES(50);
INSERT INTO exploration(area) VALUES(150);
INSERT INTO exploration(area) VALUES(500);
INSERT INTO exploration(area) VALUES(250);
INSERT INTO exploration(area) VALUES(350);
COMMIT;

--building
INSERT INTO building(exploration_id,type) VALUES(1,'stables');
INSERT INTO building(exploration_id,type) VALUES(1,'warehouse');
INSERT INTO building(exploration_id,type) VALUES(1,'garage');
INSERT INTO building(exploration_id,type) VALUES(2,'garage');
INSERT INTO building(exploration_id,type) VALUES(2,'garage');
INSERT INTO building(exploration_id,type) VALUES(2,'garage');
INSERT INTO building(exploration_id,type) VALUES(3,'garage');
INSERT INTO building(exploration_id,type) VALUES(4,'garage');
INSERT INTO building(exploration_id,type) VALUES(5,'garage');
COMMIT;

--CultureTypes
INSERT INTO CultureTypes(last_modification_date) VALUES(TO_DATE('19/12/2021', 'DD/MM/YYYY'));
INSERT INTO CultureTypes(last_modification_date) VALUES(TO_DATE('14/08/2022', 'DD/MM/YYYY'));
INSERT INTO CultureTypes(last_modification_date) VALUES(TO_DATE('25/05/2019', 'DD/MM/YYYY'));
INSERT INTO CultureTypes(last_modification_date) VALUES(TO_DATE('05/02/2018', 'DD/MM/YYYY'));
INSERT INTO CultureTypes(last_modification_date) VALUES(TO_DATE('30/01/2022', 'DD/MM/YYYY'));
COMMIT;

--Type
INSERT INTO Type(type_designation,culture_types_id) VALUES('tipo1',1);
INSERT INTO Type(type_designation,culture_types_id) VALUES('tipo2',1);
INSERT INTO Type(type_designation,culture_types_id) VALUES('tipo1',2);
INSERT INTO Type(type_designation,culture_types_id) VALUES('tipo2',2);


--culture
INSERT INTO culture(plant_species,type_id) VALUES('flores',1);
INSERT INTO culture(plant_species,type_id) VALUES('frutos',2);
INSERT INTO culture(plant_species,type_id) VALUES('cereais',3);
INSERT INTO culture(plant_species,type_id) VALUES('hortÃƒÂ­colas',3);
INSERT INTO culture(plant_species,type_id) VALUES('forragens',1);
COMMIT;

--plot
INSERT INTO plot(exploration_id,designation,area) VALUES(1,'sector',200);
INSERT INTO plot(exploration_id,designation,area) VALUES(1,'campo',1000);
INSERT INTO plot(exploration_id,designation,area) VALUES(2,'campo',750);
INSERT INTO plot(exploration_id,designation,area) VALUES(2,'sector',600);
INSERT INTO plot(exploration_id,designation,area) VALUES(3,'sector',500);
COMMIT;

--animal ration
INSERT INTO AnimalRation(animal) VALUES('Galinha');
INSERT INTO AnimalRation(animal) VALUES('Porco');
INSERT INTO AnimalRation(animal) VALUES('Vaca');
INSERT INTO AnimalRation(animal) VALUES('Ovelha');
INSERT INTO AnimalRation(animal) VALUES('Coelho');
COMMIT;

--stored culture
INSERT INTO StoredCulture(quantity,building_id,culture_id) VALUES(1000,1,1);
INSERT INTO StoredCulture(quantity,building_id,culture_id) VALUES(1500,1,3);
INSERT INTO StoredCulture(quantity,building_id,culture_id) VALUES(3000,2,2);
INSERT INTO StoredCulture(quantity,building_id,culture_id) VALUES(500,3,5);
INSERT INTO StoredCulture(quantity,building_id,culture_id) VALUES(800,3,4);
COMMIT;

--stored animal ration
INSERT INTO StoredAnimalRation(quantity,building_id,animal_ration_id) VALUES(200,1,1);
INSERT INTO StoredAnimalRation(quantity,building_id,animal_ration_id) VALUES(1500,2,2);
INSERT INTO StoredAnimalRation(quantity,building_id,animal_ration_id) VALUES(2000,2,3);
INSERT INTO StoredAnimalRation(quantity,building_id,animal_ration_id) VALUES(1000,3,4);
INSERT INTO StoredAnimalRation(quantity,building_id,animal_ration_id) VALUES(150,1,5);
COMMIT;

--production factor
INSERT INTO ProductionFactor(classification,comercial_name,formulation,type,provider) VALUES('Fertilizante','Fertilizante-A','PÃƒÂ³','Marca A', 'ADP-Fertilizantes');
INSERT INTO ProductionFactor(classification,comercial_name,formulation,type,provider) VALUES('Fertilizante','Fertilizante-B','PÃƒÂ³','Marca B', 'ADP-Fertilizantes');
INSERT INTO ProductionFactor(classification,comercial_name,formulation,type,provider) VALUES('Adubo','Adubo-A','Liquido','Marca A', 'ADP-Fertilizantes');
INSERT INTO ProductionFactor(classification,comercial_name,formulation,type,provider) VALUES('Correctivo','Correctivo-A','Granulado','Marca A', 'ADP-Fertilizantes');
INSERT INTO ProductionFactor(classification,comercial_name,formulation,type,provider) VALUES('Produto FitofÃƒÂ¡rmaco','Produto FitofÃƒÂ¡rmaco-C','PÃƒÂ³','Marca C', 'ADP-Fertilizantes');
COMMIT;

--stored production factor
INSERT INTO StoredProductionFactor(quantity,building_id,production_factor_id) VALUES(50,1,1);
INSERT INTO StoredProductionFactor(quantity,building_id,production_factor_id) VALUES(150,1,2);
INSERT INTO StoredProductionFactor(quantity,building_id,production_factor_id) VALUES(500,2,3);
INSERT INTO StoredProductionFactor(quantity,building_id,production_factor_id) VALUES(25,3,4);
INSERT INTO StoredProductionFactor(quantity,building_id,production_factor_id) VALUES(100,1,5);
COMMIT;



--metereologic station
INSERT INTO MetereologicStation(exploration_id) VALUES(1);
INSERT INTO MetereologicStation(exploration_id) VALUES(2);
INSERT INTO MetereologicStation(exploration_id) VALUES(3);
INSERT INTO MetereologicStation(exploration_id) VALUES(4);
INSERT INTO MetereologicStation(exploration_id) VALUES(5);
COMMIT;

--Sensor
INSERT INTO SENSOR(id,type,unique_number) VALUES(00001,'HS',23);
INSERT INTO SENSOR(id,type,unique_number) VALUES(00002,'TS',12);
INSERT INTO SENSOR(id,type,unique_number) VALUES(00003,'VV',10);
INSERT INTO SENSOR(id,type,unique_number) VALUES(00004,'TS',15);
INSERT INTO SENSOR(id,type,unique_number) VALUES(00005,'HA',30);
COMMIT;

--sensor data
INSERT INTO SensorData(sensor_id,record_date,value) VALUES (00001,TO_DATE('10/08/2022', 'DD/MM/YYYY'),20);
INSERT INTO SensorData(sensor_id,record_date,value) VALUES (00002,TO_DATE('11/08/2022', 'DD/MM/YYYY'),30);
INSERT INTO SensorData(sensor_id,record_date,value) VALUES (00003,TO_DATE('12/08/2022', 'DD/MM/YYYY'),40);
INSERT INTO SensorData(sensor_id,record_date,value) VALUES (00004,TO_DATE('13/08/2022', 'DD/MM/YYYY'),50);
INSERT INTO SensorData(sensor_id,record_date,value) VALUES (00005,TO_DATE('14/08/2022', 'DD/MM/YYYY'),60);
COMMIT;

--planted culture
INSERT INTO PlantedCulture(plot_id,culture_id,begin_date, end_date) VALUES (1,1,TO_DATE('11/09/2022', 'DD/MM/YYYY'),TO_DATE('12/10/2022', 'DD/MM/YYYY'));
INSERT INTO PlantedCulture(plot_id,culture_id,begin_date, end_date) VALUES (1,3,TO_DATE('12/09/2022', 'DD/MM/YYYY'),TO_DATE('13/10/2022', 'DD/MM/YYYY'));
INSERT INTO PlantedCulture(plot_id,culture_id,begin_date, end_date) VALUES (1,2,TO_DATE('13/09/2022', 'DD/MM/YYYY'),TO_DATE('14/10/2022', 'DD/MM/YYYY'));
INSERT INTO PlantedCulture(plot_id,culture_id,begin_date, end_date) VALUES (2,2,TO_DATE('14/09/2022', 'DD/MM/YYYY'),TO_DATE('15/10/2022', 'DD/MM/YYYY'));
INSERT INTO PlantedCulture(plot_id,culture_id,begin_date, end_date) VALUES (2,1,TO_DATE('15/09/2022', 'DD/MM/YYYY'),TO_DATE('16/10/2022', 'DD/MM/YYYY'));
COMMIT;

--field book
INSERT INTO FieldBook(exploration_id,creation_date, end_date, writer) VALUES (1,TO_DATE('10/08/2022', 'DD/MM/YYYY'), TO_DATE('11/08/2022', 'DD/MM/YYYY'), 'Caneta');
INSERT INTO FieldBook(exploration_id,creation_date, end_date, writer) VALUES (2,TO_DATE('11/08/2022', 'DD/MM/YYYY'), TO_DATE('12/08/2022', 'DD/MM/YYYY'), 'Caneta');
INSERT INTO FieldBook(exploration_id,creation_date, end_date, writer) VALUES (2,TO_DATE('12/08/2022', 'DD/MM/YYYY'), TO_DATE('13/08/2022', 'DD/MM/YYYY'), 'Caneta');
INSERT INTO FieldBook(exploration_id,creation_date, end_date, writer) VALUES (3,TO_DATE('13/08/2022', 'DD/MM/YYYY'), TO_DATE('14/08/2022', 'DD/MM/YYYY'), 'Caneta');
COMMIT;

--product
INSERT INTO Product(price,name,type,culture_id) VALUES (10,'ananas',1,2);
INSERT INTO Product(price,name,type,culture_id) VALUES (2,'pao',2,1);
INSERT INTO Product(price,name,type,culture_id) VALUES (100,'morango',2,3);
INSERT INTO Product(price,name,type,culture_id) VALUES (5,'milho',1,4);
COMMIT;

--harvest
INSERT INTO Harvest(plot_id,product_id,field_book_id,harvest_date, quantity) VALUES (2,1,1,TO_DATE('10/08/2022', 'DD/MM/YYYY'),20);
INSERT INTO Harvest(plot_id,product_id,field_book_id,harvest_date, quantity) VALUES (1,2,2,TO_DATE('11/08/2022', 'DD/MM/YYYY'),30);
INSERT INTO Harvest(plot_id,product_id,field_book_id,harvest_date, quantity) VALUES (1,1,1,TO_DATE('12/08/2022', 'DD/MM/YYYY'),40);
INSERT INTO Harvest(plot_id,product_id,field_book_id,harvest_date, quantity) VALUES (3,2,2,TO_DATE('13/08/2022', 'DD/MM/YYYY'),50);
INSERT INTO Harvest(plot_id,product_id,field_book_id,harvest_date, quantity) VALUES (1,2,3,TO_DATE('14/08/2022', 'DD/MM/YYYY'),60);
COMMIT;

--DistributionHub
INSERT INTO DistributionHub(address,hub_code) VALUES ('Rua da rua', 'CT1');
INSERT INTO DistributionHub(address,hub_code) VALUES ('Rua da rua2', 'CT5');
INSERT INTO DistributionHub(address,hub_code) VALUES ('Rua da rua3', 'CT8');
INSERT INTO DistributionHub(address,hub_code) VALUES ('Rua da rua4', 'CT12');
COMMIT;

--Input_hub
INSERT INTO Input_hub(loc_id,lon,lat,clients_productors) VALUES ('CT1',-54.5548,62.2215,'E1');
INSERT INTO Input_hub(loc_id,lon,lat,clients_productors) VALUES ('CT5',-1.5120,-51.3332,'P1');
INSERT INTO Input_hub(loc_id,lon,lat,clients_productors) VALUES ('CT8',89.3331,-60.0021,'P2');
INSERT INTO Input_hub(loc_id,lon,lat,clients_productors) VALUES ('CT12',-53.9986,15.2222,'P3');
COMMIT;

--ClientLevels
INSERT INTO ClientLevels(last_modification_date) VALUES(TO_DATE('19/12/2021', 'DD/MM/YYYY'));
INSERT INTO ClientLevels(last_modification_date) VALUES(TO_DATE('14/08/2022', 'DD/MM/YYYY'));
INSERT INTO ClientLevels(last_modification_date) VALUES(TO_DATE('25/05/2019', 'DD/MM/YYYY'));
INSERT INTO ClientLevels(last_modification_date) VALUES(TO_DATE('05/02/2018', 'DD/MM/YYYY'));
INSERT INTO ClientLevels(last_modification_date) VALUES(TO_DATE('30/01/2022', 'DD/MM/YYYY'));
COMMIT;

--ClientLevel
INSERT INTO ClientLevel(client_level_id, designation) VALUES(1, 'A');
INSERT INTO ClientLevel(client_level_id, designation) VALUES(2, 'B');
INSERT INTO ClientLevel(client_level_id, designation) VALUES(3, 'C');
COMMIT;

--client
INSERT INTO Client(exploration_id,name, fiscal_number, email, plafond, client_level, incident_number, last_incident_date, amount_of_orders_last_year, total_orders_value_last_year, level_id, correspondence_address, default_delivery_address, postal_code,default_hub_id) VALUES (1,'Diogo',123456789,'diogo@mail.com',1000,'A',0,NULL,4,4000, 1, 'Rua A','Rua A','4500-210',4);
INSERT INTO Client(exploration_id,name, fiscal_number, email, plafond, client_level, incident_number, last_incident_date, amount_of_orders_last_year, total_orders_value_last_year, level_id, correspondence_address, default_delivery_address, postal_code,default_hub_id) VALUES (2,'Paulo',987654321,'Paulo@gmail.com',5,'C',1,TO_DATE('14/08/2022', 'DD/MM/YYYY'),3,3000,3,'Rua brazil','Rua loureiro','3880-800',1);
INSERT INTO Client(exploration_id,name, fiscal_number, email, plafond, client_level, incident_number, last_incident_date, amount_of_orders_last_year, total_orders_value_last_year, level_id, correspondence_address, default_delivery_address, postal_code,default_hub_id) VALUES (3,'Pedro',123547698,'Pedro@gmail.com',0,'C',1,TO_DATE('14/04/2020', 'DD/MM/YYYY'),0,0,3,'Rua lizil','Rua oureiro','1380-820',2);
INSERT INTO Client(exploration_id,name, fiscal_number, email, plafond, client_level, incident_number, last_incident_date, amount_of_orders_last_year, total_orders_value_last_year, level_id, correspondence_address, default_delivery_address, postal_code,default_hub_id) VALUES (4,'Joao',213243546,'Joao@gmail.com',10,'B',3,TO_DATE('20/09/2019', 'DD/MM/YYYY'),1,25,2,'Rua il','Rua leitao','3999-230',2);
INSERT INTO Client(exploration_id,name, fiscal_number, email, plafond, client_level, incident_number, last_incident_date, amount_of_orders_last_year, total_orders_value_last_year, level_id, correspondence_address, default_delivery_address, postal_code,default_hub_id) VALUES (5,'Manuel',309876543,'Manuel@gmail.com',68,'A',0,NULL,3,3000,1,'Rua brazil','Rua loureiro','3880-800',3);
COMMIT;

--client incident
INSERT INTO ClientIncident(client_id,value, date_incident, status, remedied_date) VALUES (1,20,TO_DATE('14/08/2022', 'DD/MM/YYYY'), 'Pendente', TO_DATE('15/08/2022', 'DD/MM/YYYY'));
INSERT INTO ClientIncident(client_id,value, date_incident, status, remedied_date) VALUES (2,40,TO_DATE('20/08/2021', 'DD/MM/YYYY'), 'Paga', TO_DATE('25/08/2021', 'DD/MM/YYYY'));
INSERT INTO ClientIncident(client_id,value, date_incident, status, remedied_date) VALUES (3,60,TO_DATE('01/01/2018', 'DD/MM/YYYY'), 'Pendente', TO_DATE('20/01/2018', 'DD/MM/YYYY'));
COMMIT;

--SystemUser
INSERT INTO SYSTEMUSER(email, password, exploration_id) VALUES ('1211511@isep.ipp.pt', '1234', 1);
INSERT INTO SYSTEMUSER(email, password, exploration_id) VALUES ('1211512@isep.ipp.pt', '1234', 1);
INSERT INTO SYSTEMUSER(email, password, exploration_id) VALUES ('1211513@isep.ipp.pt', '1234', 1);
COMMIT;

--AuditLog
INSERT INTO AuditLog(operation_date, type,plot_id,system_user_id) VALUES (TO_DATE('20/01/2018', 'DD/MM/YYYY'), 'type',1,1);
INSERT INTO AuditLog(operation_date, type,plot_id,system_user_id) VALUES (TO_DATE('22/01/2018', 'DD/MM/YYYY'), 'type',3,1);
INSERT INTO AuditLog(operation_date, type,plot_id,system_user_id) VALUES (TO_DATE('24/01/2018', 'DD/MM/YYYY'), 'type',2,2);
COMMIT;

--Operation
INSERT INTO Operation(plot_id,status) VALUES (1,'PENDENTE');
INSERT INTO Operation(plot_id,status) VALUES (1,'COMPLETO');
INSERT INTO Operation(plot_id,status) VALUES (2,'CANCELADO');
INSERT INTO Operation(plot_id,status) VALUES (2,'PENDENTE');
COMMIT;

--Plot Restrictions
INSERT INTO PLOTRESTRICTIONS(plot_id, production_factor_id, restriction_begining_date, restriction_end_date) VALUES(1, 1, TO_DATE('24/05/2019', 'DD/MM/YYYY'), TO_DATE('30/05/2020', 'DD/MM/YYYY'));
INSERT INTO PLOTRESTRICTIONS(plot_id, production_factor_id, restriction_begining_date, restriction_end_date) VALUES(1, 2, TO_DATE('10/04/2019', 'DD/MM/YYYY'), TO_DATE('10/05/2019', 'DD/MM/YYYY'));
INSERT INTO PLOTRESTRICTIONS(plot_id, production_factor_id, restriction_begining_date, restriction_end_date) VALUES(2, 2, TO_DATE('30/05/2019', 'DD/MM/YYYY'), TO_DATE('30/05/2021', 'DD/MM/YYYY'));
INSERT INTO PLOTRESTRICTIONS(plot_id, production_factor_id, restriction_begining_date, restriction_end_date) VALUES(2, 3, TO_DATE('29/05/2018', 'DD/MM/YYYY'), TO_DATE('30/05/2020', 'DD/MM/YYYY'));
COMMIT;

--ElementType
INSERT INTO ElementType(designation) VALUES ('Fertilizante');
INSERT INTO ElementType(designation) VALUES ('Agua');
INSERT INTO ElementType(designation) VALUES ('Ã“leo');
INSERT INTO ElementType(designation) VALUES ('OxigÃ©nio');
INSERT INTO ElementType(designation) VALUES ('Herbicida');
COMMIT;

--GenericElement
INSERT INTO GenericElement(name, element_type_id) VALUES('Fertilizante', 1);
INSERT INTO GenericElement(name, element_type_id) VALUES('Agua', 2);
INSERT INTO GenericElement(name, element_type_id) VALUES('Ã“leo', 3);
INSERT INTO GenericElement(name, element_type_id) VALUES('OxigÃ©nio', 4);
INSERT INTO GenericElement(name, element_type_id) VALUES('Herbicida', 5);
COMMIT;

--TechnicalSheetAssociation
INSERT INTO TechnicalSheetAssociation(production_factor_id, generic_elemnet_id, quantity) VALUES(1, 1, 10);
INSERT INTO TechnicalSheetAssociation(production_factor_id, generic_elemnet_id, quantity) VALUES(2, 1, 30);
INSERT INTO TechnicalSheetAssociation(production_factor_id, generic_elemnet_id, quantity) VALUES(3, 2, 40);
INSERT INTO TechnicalSheetAssociation(production_factor_id, generic_elemnet_id, quantity) VALUES(4, 3, 100);
INSERT INTO TechnicalSheetAssociation(production_factor_id, generic_elemnet_id, quantity) VALUES(5, 1, 20);
COMMIT;

--GenericElement
INSERT INTO GenericElement(name, element_type_id) VALUES('Fertilizante', 1);
INSERT INTO GenericElement(name, element_type_id) VALUES('Agua', 2);
INSERT INTO GenericElement(name, element_type_id) VALUES('Ã“leo', 3);
INSERT INTO GenericElement(name, element_type_id) VALUES('OxigÃ©nio', 4);
INSERT INTO GenericElement(name, element_type_id) VALUES('Herbicida', 5);
COMMIT;

--ElementType
INSERT INTO ElementType(designation) VALUES('Fertilizante');
INSERT INTO ElementType(designation) VALUES('Agua');
INSERT INTO ElementType(designation) VALUES('Ã“leo');
INSERT INTO ElementType(designation) VALUES('OxigÃ©nio');
INSERT INTO ElementType(designation) VALUES('Herbicida');
COMMIT;

--Irrigation 
INSERT INTO Irrigation(irrigation_minutes,type,field_book_id,operation_id) VALUES (20,1,1,1); 
INSERT INTO Irrigation(irrigation_minutes,type,field_book_id,operation_id) VALUES (10,1,3,2); 
INSERT INTO Irrigation(irrigation_minutes,type,field_book_id,operation_id) VALUES (15,2,2,1); 
COMMIT;

--ProductionFactorApplication
INSERT INTO ProductionFactorApplication(production_factor_id,type,field_book_id,quantity_applied,operation_id) VALUES(1,1,2,10,1);
INSERT INTO ProductionFactorApplication(production_factor_id,type,field_book_id,quantity_applied,operation_id) VALUES(3,2,1,20,2);
INSERT INTO ProductionFactorApplication(production_factor_id,type,field_book_id,quantity_applied,operation_id) VALUES(2,1,3,5,1);
INSERT INTO ProductionFactorApplication(production_factor_id,type,field_book_id,quantity_applied,operation_id) VALUES(3,2,1,10,3);
COMMIT;



--BasketOrder
INSERT INTO BasketOrder(client_id, delivery_address, status, order_date, total_amount, pickup_hub_id) VALUES(1, 'Rua DÃ£o Afonso 301', 'Paga',  TO_DATE('19/12/2021', 'DD/MM/YYYY'), 10, 1);
INSERT INTO BasketOrder(client_id, delivery_address, status, order_date, total_amount, pickup_hub_id) VALUES(2, 'Rua FamÃ­lia Fonseca 101', 'Registada',  TO_DATE('14/08/2022', 'DD/MM/YYYY'), 20, 2);
INSERT INTO BasketOrder(client_id, delivery_address, status, order_date, total_amount, pickup_hub_id) VALUES(3, 'Rua da Alameda 205', 'Entregue',  TO_DATE('25/05/2019', 'DD/MM/YYYY'), 30, 3);
INSERT INTO BasketOrder(client_id, delivery_address, status, order_date, total_amount, pickup_hub_id) VALUES(4, 'Rua da CircunvalaÃ§Ã£o 90', 'Paga',  TO_DATE('05/02/2018', 'DD/MM/YYYY'), 40, 4);
INSERT INTO BasketOrder(client_id, delivery_address, status, order_date, total_amount, pickup_hub_id) VALUES(2, 'Rua das Chinas 31', 'Entregue',  TO_DATE('30/01/2022', 'DD/MM/YYYY'), 50, 1);
COMMIT;	

--BasketProduct
INSERT INTO BasketProduct(basket_order_id, product_id, quantity) VALUES(1, 1, 1);
INSERT INTO BasketProduct(basket_order_id, product_id, quantity) VALUES(2, 2, 2);
INSERT INTO BasketProduct(basket_order_id, product_id, quantity) VALUES(3, 3, 3);
INSERT INTO BasketProduct(basket_order_id, product_id, quantity) VALUES(4, 4, 4);
INSERT INTO BasketProduct(basket_order_id, product_id, quantity) VALUES(5, 3, 5);
COMMIT;

--OrderDelivery
INSERT INTO OrderDelivery(delivery_date, basket_order_id) VALUES(TO_DATE('19/12/2021', 'DD/MM/YYYY'), 1);
INSERT INTO OrderDelivery(delivery_date, basket_order_id) VALUES(TO_DATE('15/01/2022', 'DD/MM/YYYY'), 2);
INSERT INTO OrderDelivery(delivery_date, basket_order_id) VALUES(TO_DATE('23/02/2019', 'DD/MM/YYYY'), 3);
INSERT INTO OrderDelivery(delivery_date, basket_order_id) VALUES(TO_DATE('01/09/2018', 'DD/MM/YYYY'), 4);
INSERT INTO OrderDelivery(delivery_date, basket_order_id) VALUES(TO_DATE('30/07/2022', 'DD/MM/YYYY'), 5);
COMMIT;

--OrderPayment
INSERT INTO OrderPayment(payment_date, basket_order_id) VALUES(TO_DATE('13/02/2021', 'DD/MM/YYYY'), 1);
INSERT INTO OrderPayment(payment_date, basket_order_id) VALUES(TO_DATE('24/11/2022', 'DD/MM/YYYY'), 2);
INSERT INTO OrderPayment(payment_date, basket_order_id) VALUES(TO_DATE('15/06/2019', 'DD/MM/YYYY'), 3);
INSERT INTO OrderPayment(payment_date, basket_order_id) VALUES(TO_DATE('25/10/2018', 'DD/MM/YYYY'), 4);
INSERT INTO OrderPayment(payment_date, basket_order_id) VALUES(TO_DATE('12/04/2022', 'DD/MM/YYYY'), 5);
COMMIT;

INSERT INTO Operation_Calendar(operation_id,start_date,end_date) VALUES(1,TO_DATE('19/10/2021', 'DD/MM/YYYY'),TO_DATE('29/10/2021', 'DD/MM/YYYY'));
INSERT INTO Operation_Calendar(operation_id,start_date,end_date) VALUES(2,TO_DATE('19/10/2021', 'DD/MM/YYYY'),TO_DATE('29/10/2021', 'DD/MM/YYYY'));
INSERT INTO Operation_Calendar(operation_id,start_date,end_date) VALUES(3,TO_DATE('19/10/2021', 'DD/MM/YYYY'),TO_DATE('20/10/2021', 'DD/MM/YYYY'));
INSERT INTO Operation_Calendar(operation_id,start_date,end_date) VALUES(4,TO_DATE('19/10/2021', 'DD/MM/YYYY'),TO_DATE('29/10/2021', 'DD/MM/YYYY'));
COMMIT;

--InputSensor
INSERT INTO input_sensor(input_string) VALUES('00001HS10065201220202000');
INSERT INTO input_sensor(input_string) VALUES('00001HS10065201220202001');
INSERT INTO input_sensor(input_string) VALUES('00001HS100652012202020000');
INSERT INTO input_sensor(input_string) VALUES('00002HS100652012202020000');
INSERT INTO input_sensor(input_string) VALUES('00001HS10065201220202000');
