#include <stdio.h>
#include <stdint.h>
#include "pcg32_random_r.h"

int state = 0;
int inc = 0;


int generate_random(){														//function to generate a random number 
	
	int buffer [64]; 														//create an 64 bits array
    FILE *f;					
    int result;					
    int i;
    
    f = fopen("/dev/urandom", "r");  										//get the file dev/urandom
    if (f == NULL) {														//Error if the file was not found
        printf("Error: open() failed to open /dev/random for reading\n"); 
        return 1;
        }
    result = fread(buffer , sizeof(char), 64,f);							//fill the array of random numbers
    if (result < 1) {														//Error if was not possible read the random numbers generated by the file
        printf("error , failed to read and words\n"); 						
        return 1;
    }
    
	for(i=0;i<result;i++){																								
		state = buffer[i];												//update num
		inc = buffer[i+1];												//update inc
		int ran = pcg32_random_r();										//ran = random number 
			
		return ran; 													//return ran
	}	
	
	return 0;
}
