@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "System User" as user

activate user

user -> ":System" : requests to import data
activate ":System"
":System" --> user : requests data (entity file, connections file)
deactivate ":System"

user -> ":System" : inputs data
activate ":System"
":System" --> user : informs success/failure message
deactivate ":System"


@enduml